### ISSUE TITLE
Notice error in Product Iterator when generating feed

### ISSUE THREAD

**Issue by igorwulff** [EmicoEcommerce/Magento2TweakwiseExport-archived#10]
Issue Brief
--
When performing php/bin magento tweakwise:export we get a notice error:
[Exception]                                                                                                                         
  Notice: Undefined offset: 36 in vendor/emico/tweakwise-export/src/Model/Write/Products/Iterator.php on line 376 

This is for the first product in our catalog. When we skip this entity_id in the code for testing purposes it falls over the next product. We did this because the first product was not in stock and not visible. But the second product was an active product. Still the notice appeared. We are unsure how to proceed now and it seems to be a bug in the Tweakwise Export functionality.

Environment
--
* PHP Version: 7.0
* Magento Version: 2.1.7
* Tweakwise Export Version: v1.0.0
* Magento Deploy Mode: production

**Comment by Fgruntjes** [comment]
Please update to the latest version and try again. Although I am not 100% sure this will fix the issue with the current provided information we can not reproduce the issue. Please provide us with the database you are trying to run an export with if the issue still exists after an update.

**Comment by Fgruntjes** [comment]
Hello,

Did this fix the issue for you?

**Comment by igorwulff** [comment]
Hi @Fgruntjes, we did install the latest version but are now unable to access Tweakwise in the System Configuration now. We also don't see Tweakwise options when performing bin/magento. Something seems wrong with the latest version.

**Comment by igorwulff** [comment]
hi @Fgruntjes, just discussed this with a colleague, who says there is an error in the registration.php file and that this has been fixed on dev-master. We will try to update to dev-master on our own staging/test environment.

**Comment by igorwulff** [comment]
Hi @Fgruntjes,
This seems to have resolved our issue. When will this be released as stable?

**Comment by igorwulff** [comment]
@Fgruntjes,

We have tested this on production, and have the same error. So this did not resolve the issue. The client really needs this functionality, can you check this further?

**Comment by Fgruntjes** [comment]
@igorwulff 

We are happy to investigate this further however we really would need a situation we can reproduce. 

Could you provide us with a striped version of your database where the issues exists so we can test using this data.

**Comment by Fgruntjes** [comment]
@igorwulff 
Would it be possible for you to provide the database today? If so we can add this issue to the release of today.

**Comment by igorwulff** [comment]
Hoi @Fgruntjes,
Which tables do you need to be able to test this properly?

**Comment by Fgruntjes** [comment]
All the catalog related tables would be required. However it is also required that the database is a working environment so dropping tables completely is not an option.

We suggest to create a local copy, clear all customer related tables and then make a dump for us.

**Comment by Fgruntjes** [comment]
Just added a possible fix for the issue, can you confirm that the issue now has been resolved?

Kind regards,
Freek

**Comment by igorwulff** [comment]
Hi @Fgruntjes,

Thanks for replying. The issue now suddenly doesn't appear during export with the older version. I have not yet updated it on production and the only changes are the ongoing mutations on product/category/stock data not beyond normal behavior. Still it might be causes by the same, but we can't check right now. 

Let's close the ticket, update the extension and see if it arises again or not. Thanks for the help!
