### ISSUE TITLE
Error while running php bin/magento setup:di:compile

### ISSUE THREAD

**Issue by edwinknol-mediact** [EmicoEcommerce/Magento2TweakwiseExport-archived#11]
Issue Brief
--
What is the purpose of this issue? Explain the background context.
I'm trying to run php bin/magento setup:di:compile

Environment
--
* PHP Version: (7.0)
* Magento Version: 2.1.7
* Tweakwise Export Version: 1.0.1
* Magento Deploy Mode: (development)
* Third party modules:

Steps to reproduce
--
From the commandline: run php bin/magento setup:di:compile

See http://prntscr.com/fs945i

Actual result
--
[ReflectionException]
Class   does not exist

Expected result
--
Succesfull di:compile

Suggestion
--
vendor/emico/tweakwise-export/src/registration.php should look like this:

\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::MODULE,
    'Emico_TweakwiseExport',
    __DIR__
);

**Comment by Fgruntjes** [comment]
Duplicated with #9
