### ISSUE TITLE
Incorrect Class Name Check

### ISSUE THREAD

**Issue by binohartoko** [EmicoEcommerce/Magento2TweakwiseExport-archived#12]
Issue Brief
--
On the https://github.com/EmicoEcommerce/Magento2TweakwiseExport/blob/master/src/registration.php

There is incorrect class name check.
Instead of 'Magento\Framework\Component\ComponentRegistrar\ComponentRegistrar', It should be 'Magento\Framework\Component\ComponentRegistrar'.

It makes module will always not be installed.

Environment
--
 *   PHP Version: 7.0
 *   Magento Version: 2.1.7
 *   Tweakwise Export Version: v1.0.2
 *   Magento Deploy Mode: production

**Comment by Fgruntjes** [comment]
You are 100% right, thank you!
