### ISSUE TITLE
Category With entity_id Lower Than parent_id Is Not Imported

### ISSUE THREAD

**Issue by binohartoko** [EmicoEcommerce/Magento2TweakwiseExport-archived#13]
Issue Brief
--
When rearrange category tree (by drag and drop fro example), there is possibility that entity_id of that category lower that parent_id. When this case is happened, the category will not be exported into tweakwise.

Environment
--
* PHP Version: (5.6|7.0|7.1)
* Magento Version: 2.1.7
* Tweakwise Export Version: v1.0.2
* Magento Deploy Mode: production

Steps to reproduce
--
1. Go to category page of admin page
2. Move category so we have entity_id lower that parent_id
3. Export data into tweakwise
4. Go to frontend of category page of the parent_id
5. Go also to tweakwise account page

Actual result
--
1. Category page of parent_id has empty product
2. In the tweakwise account page, there is NO category with specify entity_id under the category of specify parent_id

Expected result
--
- If category with specify entity_id has products, the products should be there on that category page
- In the tweakwise account page, there is the category with specify entity_id under the category of specify parent_id

**Comment by binohartoko** [comment]
Hi,

Could you please confirm if this is known issue or only my issue.

Regards,
Bino Hartoko

**Comment by binohartoko** [comment]
Confirm that this is the tweakwise exported issue. I reorder the sort so it will make sure that parent row will be listed before it's childs. It works.

I save my changes into this attached patch.


[tweakwise-export-category.patch.zip](https://github.com/EmicoEcommerce/Magento2TweakwiseExport/files/1186512/tweakwise-export-category.patch.zip)

**Comment by igorwulff** [comment]
@Fgruntjes can you come back to this ticket?

**Comment by Fgruntjes** [comment]
@binohartoko 

Would you mind converting your patch into a pull request? We are happy to accept this as an improvement on the extension.
