### ISSUE TITLE
Export command doesn't work

### ISSUE THREAD

**Issue by maksymhryb** [EmicoEcommerce/Magento2TweakwiseExport-archived#14]
Export command doesn't work
--
After releasing version 1.0.3 export command doesn't work for me.
I have an assumption that bug occurs only for Community Edition, since methods for generating queries for CE and EE are different.

Environment
--
* PHP Version: (5.6|7.0|7.1)
* Magento Version: Magento 2.1.6 CE
* Tweakwise Export Version: 1.0.3
* Magento Deploy Mode: (production|development) both

Steps to reproduce
--
1. Install Magento CE from `develop` branch.
2. Install Tweakwise FeedExport v1.0.3
2. Execute command bin/magento tweakwise:export

Actual result
- An error occurred:
 [Zend_Db_Statement_Exception]                                                                                                                                                       

>   SQLSTATE[42S22]: Column not found: 1054 Unknown column 'path' in 'order clause', query was: SELECT `catalog_category_entity`.`entity_id`, 0 AS `store_id`, 'parent_id' AS `attribu  
>   te_id`, `catalog_category_entity`.`parent_id` AS `value` FROM `catalog_category_entity` UNION SELECT `catalog_category_entity`.`entity_id`, 0 AS `store_id`, 46 AS `attribute_id`,  
>    `catalog_category_entity`.`path` AS `value` FROM `catalog_category_entity` UNION SELECT `catalog_category_entity`.`entity_id`, 0 AS `store_id`, 57 AS `attribute_id`, `catalog_ca  
>   tegory_entity`.`level` AS `value` FROM `catalog_category_entity` UNION SELECT `catalog_category_entity`.`entity_id`, 0 AS `store_id`, 47 AS `attribute_id`, `catalog_category_enti  
>   ty`.`position` AS `value` FROM `catalog_category_entity` UNION SELECT `catalog_category_entity_varchar`.`entity_id`, `catalog_category_entity_varchar`.`store_id`, `catalog_catego  
>   ry_entity_varchar`.`attribute_id`, `catalog_category_entity_varchar`.`value` FROM `catalog_category_entity_varchar` WHERE (attribute_id IN (35)) AND (store_id = 0 OR store_id = 3  
>   ) UNION SELECT `catalog_category_entity_int`.`entity_id`, `catalog_category_entity_int`.`store_id`, `catalog_category_entity_int`.`attribute_id`, `catalog_category_entity_int`.`v  
>   alue` FROM `catalog_category_entity_int` WHERE (attribute_id IN (36)) AND (store_id = 0 OR store_id = 3) ORDER BY `path` ASC                 
                                                                                     
Expected result
- Feed exported successfully

**Comment by Fgruntjes** [comment]
We made a mistake implementing the fix for issue #13, this should now be fixed completely with 65e3b2fc4a746310260a5ad7f4ad978c3852e2af.
