### ISSUE TITLE
Functionality to also use attributes outside the flat table

### ISSUE THREAD

**Issue by igorwulff** [EmicoEcommerce/Magento2TweakwiseExport-archived#17]
Issue Brief
--
For Magento 1 there is an option for the Tweakwise Export to use the flat index or not, for the feed creation. I don't see this option for Magento 2, but we require it for one of our clients. Is this something that can be added to the extension?

**Comment by igorwulff** [comment]
Or is this already setup this way for Tweakwise, @Fgruntjes? I'm analyzing the code, it's not entirely clear yet. So hope you can clarify where the export is based on, flat, eav or both?

**Comment by Fgruntjes** [comment]
Hello,

This is already how the extension was set up. We do not use the flat tables any longer for the export.

All attributes with either one of these settings enabled will be exported:
```php
/**
 * @param Attribute $attribute
 * @return bool
 */
public function shouldExportAttribute(Attribute $attribute)
{
    if (
        !$attribute->getUsedInProductListing() &&
        !$attribute->getIsFilterable() &&
        !$attribute->getIsFilterableInSearch() &&
        !$attribute->getIsFilterableInGrid() &&
        !$attribute->getIsSearchable() &&
        !$attribute->getIsVisibleInAdvancedSearch() &&
        !$attribute->getUsedForSortBy()
    ) {
        return false;
    }

    return true;
}
```

On top of this some attributes are always exported like: price, min_price, max_price, sku, name and stock.

Kind regards,
Freek
