### ISSUE TITLE
Stock is 0 but has stock in magento

### ISSUE THREAD

**Issue by martijnrmediact** [EmicoEcommerce/Magento2TweakwiseExport-archived#20]
The stock qty for simple products is not correct. For almost all products a stock of 0 is in the feed but the product has a correct stock of for example 2300.

Environment
--
* PHP Version: 7.0
* Magento Version: Magento EE 2.1.9
* Tweakwise Export Version: latest
* Magento Deploy Mode: production

Steps to reproduce
--
1. Have products with a stock of for exampl 2600
2. Run the export
3. Product has a stock of 0 in the feed

Actual result
--
1. Product should have a correct stock qty in the feed

**Comment by JKingma** [comment]
@Fgruntjes Confirm this issue for another client on the same environment variables

**Comment by binohartoko** [comment]
I have created a pull request on https://github.com/EmicoEcommerce/Magento2TweakwiseExport/pull/21
to fix this issue.
