### ISSUE TITLE
Undefined Method getStockThresholdQty

### ISSUE THREAD

**Issue by joost-florijn-kega** [EmicoEcommerce/Magento2TweakwiseExport-archived#23]
Issue Brief
--
Export failed because of the following error message:
```
[Thu Oct 26 07:28:26.236836 2017] [proxy_fcgi:error] [pid 2360] [client 192.168.33.1:49952] AH01071: Got error 'PHP message: PHP Fatal error:  Method Emico\\TweakwiseExport\\App\\Response\\FeedContent::__toString() must not throw an exception, caught Error: Call to undefined method Magento\\CatalogInventory\\Model\\Configuration::getStockThresholdQty() in vendor/zendframework/zend-http/src/Response.php on line 0\n'
```

I have traced this back to the following line:
https://github.com/EmicoEcommerce/Magento2TweakwiseExport/blob/master/src/Model/Write/Products/Iterator.php#L244

Environment
--
* PHP Version: 7.0
* Magento Version: 2.1.9
* Tweakwise Export Version: 1.0.7
* Magento Deploy Mode: production

Steps to reproduce
--
1. Install Magento from `develop` branch.
2. Export the feed.

Actual result
--
1. PHP Fatal error: 
```
[Thu Oct 26 07:28:26.236836 2017] [proxy_fcgi:error] [pid 2360] [client 192.168.33.1:49952] AH01071: Got error 'PHP message: PHP Fatal error:  Method Emico\\TweakwiseExport\\App\\Response\\FeedContent::__toString() must not throw an exception, caught Error: Call to undefined method Magento\\CatalogInventory\\Model\\Configuration::getStockThresholdQty() in vendor/zendframework/zend-http/src/Response.php on line 0\n'
```

Expected result
--
List the expected results as a bullet list of expectations
- [ ] That the file tweakwise.xml is successfully created.
- [ ] That the import by Tweakwise is triggered.

**Comment by Fgruntjes** [comment]
Hello,

Are you using Magento CE or EE?

Kind regards.
Freek

**Comment by LarsRezelman** [comment]
Hi Freek,

We are using Magento Enterprise Edition.

Kind Regards,
Lars
