### ISSUE TITLE
Command bin/magento tweakwise:export throws error

### ISSUE THREAD

**Issue by basselalaraaj** [EmicoEcommerce/Magento2TweakwiseExport-archived#27]
Issue Brief
--
When i run bin/magento tweakwise:export in the cli it returns that u are trying to set an area named "crontab" but an area is already set named "adminhtml".

Environment
--
- [x] PHP Version: PHP 7.0
- [x] Magento Version: 2.1.9
- [x] Magento Enterprise: (yes)
- [x] Tweakwise Export Version: 1.0.8
- [x] Magento Deploy Mode: (production)

Steps to reproduce
--
1. Run the command bin/magento tweakwise:export -vvv in cli

Actual result
--
![screen shot 2017-11-09 at 09 40 29](https://user-images.githubusercontent.com/5745279/32596903-3052ea2c-c535-11e7-97e6-2576f05de9c7.png)

Expected result
--
![screen shot 2017-11-09 at 10 03 27](https://user-images.githubusercontent.com/5745279/32596919-43129040-c535-11e7-9c1b-c8f099c809a8.png)

**Comment by Fgruntjes** [comment]
This is an issue with your Magento install to be sure. However to make the whole extension a bit more robust we changed this to emulating the environment. This should help your case.
