### ISSUE TITLE
Duplicate product entries in feed

### ISSUE THREAD

**Issue by mdubbelman** [EmicoEcommerce/Magento2TweakwiseExport-archived#3]
We are getting duplicate entries in the tweakwise export feed.

--
When we are exporting the products via the tweakwise export module everything looks OK and the feed is generated. But when we try to import the feed in the Tweakwise Navigator we get an error because of dupicate ID's

Environment
--
* PHP Version: 7.0
* Magento Version: 2.1.6 CE
* Tweakwise Export Version: latest
* Magento Deploy Mode: production & development
* Third party modules: TIG_buckaroo

Steps to reproduce
--
1. Install Magento from `develop` branch.
2. Export the products via the command `php bin/magento tweakwise:export`
3. Feed is generated, but with duplicate entries

Actual result
--
- Duplicate ID's in generated feed:
![screen shot 2017-05-02 at 2 54 31 pm](https://cloud.githubusercontent.com/assets/393123/25618455/4b9bcf8a-2f47-11e7-9810-e0d00a55b557.png)

- The product ID exists only 1 time in the database

Expected result
--
- 1 entry per product / store combination

--
Maybe there must be a `group by` or `DISTINCT` in the product selection query?

**Comment by Fgruntjes** [comment]
Hello,

Unfortunately we could not reproduce the issue with the Magento test data. Could you send me the database (fgruntjes@emico.nl) or give access to the test environment so we can debug the issue there. 

If thats an option please send the information to fgruntjes@emico.nl or give access using my public key.
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3lL78eUCbw9cxooQICUtzIGBtJrh13rHaUuepQAHUZtFRFfWc1wxouqzTuixIBgdAxJk1tmexUUPzp4lZkCuRVqlK3pabKwBTSazGSB20+AdEfPmDt+E/yDWfRTfBdxEnRcpaTqiAs2ygYfjX+RvIFinOoovuI0HATVUnv3CbaQTR1QFAhG73GNxLaeI/R8rUMtStpiL0YiQgZzVUCFY6FnLvoMLcn+p9AN+lD1KH6caJ4PoCMyE83Rc/20fM3S/Q41mMgl8n/SkyleWN409e1EpmuMYx15rIliKXQoPYmpBsnzRW3IPgYXuW0oJsHg8fzYZosaP1HYaeqcl6X+3D fgruntjes@emico.nl
```

**Comment by Fgruntjes** [comment]
Thank you for your input.

The issue was caused because we forgot to clear the write batch in the product iterator.
