### ISSUE TITLE
Out of stock producten alsnog in Tweakwise

### ISSUE THREAD

**Issue by LarsRezelman** [EmicoEcommerce/Magento2TweakwiseExport-archived#31]
Issue: Er komen producten van Magento in Tweakwise die een status hebben out of stock. Deze producten hebben in Magento de status Out of Stock. In Twekawise hebben deze de status In Stock. Neem bijvoorbeeld:
 - EGO>DRIZZLE
 -- Magento: Stock status: Out of Stock
 -- Tweakwise: quantity_and_stock_status In Stock
 - Union Okayama
 -- Magento: Stock status: Out of Stock
 -- quantity_and_stock_status	In Stock

In Magento is de configurable: out of stock
Het product heeft een out of stock treshold van 2 bij onze klant.
De configurable of de simple heeft in dat geval bijvoorbeeld nog 1 of 2 stock staan, maar daardoor dus niet meer verkoopbaar.
Toch werden deze producten ingelezen in Tweakwise. Ik heb , ter test, voor beide de stock naar 0 aangepast en nu komen deze niet meer nar Tweakwise. Daar moet dus nog meer logica in gemaakt worden.

Environment
--
- [ ] PHP Version: (7.0)
- [ ] Magento Version: 2.1.10
- [ ] Magento Enterprise: (yes|)
- [ ] Tweakwise Export Version: latest: v1.0.10
- [ ] Magento Deploy Mode: (production)

**Comment by Fgruntjes** [comment]
Hallo,

Wij hebben dit getest maar kunnen het issue niet reproduceren. Zou je van de volgende tabellen de data van de genoemde producten aan kunnen leveren.
- catalog_product_bundle_selection
- catalog_product_entity
- catalog_product_entity_datetime
- catalog_product_entity_decimal
- catalog_product_entity_gallery
- catalog_product_entity_int
- catalog_product_entity_text
- catalog_product_entity_varchar
- catalog_product_index_price
- catalog_product_super_link
- catalog_product_website
- cataloginventory_stock
- cataloginventory_stock_item

Daarnaast ook de configuratie instellingen van de export extensie.

Alvast bedankt.

Groeten,
Freek

**Comment by LarsRezelman** [comment]
Beste Freek,

In overleg met onze ontwikkelaar zou dit ticket goed te moeten reproduceren zijn. Hebben jullie onderstaande al toegepast?

Om dit te reproduceren dien je op de volgende plekken in Magento de stock treshold in te stellen:
Config/catalog/inventory/product stock options/out-of-stock Treshold aanpassen naar bijv. 2.
Config/catalog/Visual Merchandiser/General Options/Minimum Stock Treshold aanpassen naar bijv. 2.

Vervolgens zou je producten moet creëren/opzoeken waarvan de simples 1 of 2 stock hebben waardoor de simple niet te verkopen is.

In het geval van onze implementatie van Score wordt de stock default bijgehouden.

Met vriendelijke groet,
Lars Rezelman

**Comment by LarsRezelman** [comment]
@Fgruntjes , Om alle verwarring met de andere tickets te voorkomen. Heb jij van ons nu iets nodig om dit te kunnen reproduceren? Zo ja, dan kan je altijd morgen direct contact met ons op nemen zodat wij jou daarbij kunnen helpen, zonder vertraging.

**Comment by Fgruntjes** [comment]
Er waren inderdaad een aantal issues omtrend configurables en stock configuratie. Hier zijn tests voor gemaakt en deze zijn hersteld.

Alleen voor de multistore zaken hebben we nog geen tests voor gemaakt. Kunnen jullie dit zelf even testen met de huidige laatste versie uit master?

**Comment by LarsRezelman** [comment]
@Fgruntjes ,
Op dit moment geeft Tweakwise een training aan Score. Dit zou rond 1400 / 1430 afgerond zijn. Vervolgens kan ik dit op onze omgeving inderdaad gaan testen.

Wij kunnen de nieuwste versie dus nu op onze omgeving zetten?

**Comment by Fgruntjes** [comment]
Hoi @LarsRezelman 

Ja je kunt dus testen met een nieuwe versie, maar zoals gezegd heb ik niet kunnen testen op een correcte multistore omgeving.

**Comment by LarsRezelman** [comment]
Hi @Fgruntjes ,
We hebben gisteren al met versie 1.0.11 getest. Hieruit kwam probleem: https://github.com/EmicoEcommerce/Magento2TweakwiseExport/issues/34.
Daardoor werkt onze omgeving niet meer.

We wachten de nieuwe versie af om te testen.

**Comment by Fgruntjes** [comment]
Issue have been fixed with the latest version V1.0.12
