### ISSUE TITLE
Prijzen worden verkeerd uit de Magento Prijs index gehaald

### ISSUE THREAD

**Issue by LarsRezelman** [EmicoEcommerce/Magento2TweakwiseExport-archived#32]
Issue: De prijs komt nog steeds niet altijd goed binnen bij de klant Score, na het importeren van de Magento gegevens waardoor prijs uit de prijs index, en wordt het nog steeds 9999. Neem bijvoorbeeld:
- Union Okayama
-- In Magento voor de Score storevies (id 1 en Id 5) in de prijs index 199,95
-- In Tweakwise voor Score (id 1 en id 5): 999999
- Ego Aqua
-- In Magento voor de Score storevies (id 1 en Id 5) in de prijsindex 59,98
-- In Tweakwise voor Score (id 1 en id 5): 999999
- Loas
-- In Magento voor de Score en Chasin in de prijsindex: 59,95
-- In Tweakwise voor Score en Chasin: 999999

Environment
--
- [ ] PHP Version: (7.0)
- [ ] Magento Version: 2.1.10
- [ ] Magento Enterprise: (yes)
- [ ] Tweakwise Export Version:latsest:1.0.10
- [ ] Magento Deploy Mode: (production)

**Comment by Fgruntjes** [comment]
Hallo,

Wij hebben dit getest maar kunnen het issue niet reproduceren. Zou je van de volgende tabellen de data van de genoemde producten aan kunnen leveren.
- catalog_product_bundle_selection
- catalog_product_entity
- catalog_product_entity_datetime
- catalog_product_entity_decimal
- catalog_product_entity_gallery
- catalog_product_entity_int
- catalog_product_entity_text
- catalog_product_entity_varchar
- catalog_product_index_price
- catalog_product_super_link
- catalog_product_website
- cataloginventory_stock
- cataloginventory_stock_item

Daarnaast ook de configuratie instellingen van de export extensie.

Alvast bedankt.

Groeten,
Freek

**Comment by LarsRezelman** [comment]
Goedemorgen Freek,

Ik heb met mijn ontwikkelaar naar jouw verzoek gekeken of we van deze producten diverse index tabellen kunnen aanleveren.

Voordat dat nodig is, zagen wij toen wij hier verder naar aan het kijken waren, dat deze producten geen eens in Tweakwise hadden mogen staan, vanwege diverse redenen.

Goed om te weten is dat Score heeft 2 websites Score en Chasin'. Score verkoopt meerdere merken kleding, waaronder het merk Chasin. Chasin verkoopt het merk Chasin. Er is dus overlap in de producten. Per website kunnen de producten een andere voorraad of prijs hebben, of zelf in- of uitgeschakeld of dus in- of out of stock zijn.

Het probleem met de prijzen hoeft wellicht geen eens voor te komen als deze producten niet in Tweakwise komen. Van deze producten zijn simples niet meer te koop. De configurabele zou dan niet meer te koop moeten zijn. Bij de ze producten zien we dat of voor 
- Union Okayama:
Zowel Score als Chasin zijn de simples niet te koop. Hierdoor zouden beide producten niet in Tweakwise moeten staan.
Configurable disabled, status = out of stock, qnty = 0 voor Score en Chasin
Er is 1 simple met stock 2, status = disabled voor Score. Op default en Chasin is de status enabled. Maar door de out of stock treshold kan deze simple niet verkocht worden.

- Ego Aqua:
Zowel Score zijn de simples niet te koop, Bij Chasin nog wel 1 verkoopbare simple. Hierdoor zou het product niet in Tweakwise moeten staan voor Score, enkel voor Chasin.
Configurable enabled, status = in stock, qnty = 0
Er is 1 simple met stock 20, status = disabled voor Score. Op default en Chasin is de status enabled.

- Loas:
Zowel Score als Chasin zijn de simples niet te koop. Hierdoor zouden beide producten niet in Tweakwise moeten staan.
Configurable enabled, status = in stock, qnty = 0
Alle simples zijn voor Score en Chasin disabled, en hadden een stock van max 1. Op default staan de simples wel nog in stock.

Het ziet er naar uit dat de prijs 99999 wordt als dit product niet in Tweakwise heeft mogen staan. Daarom kan beter de oorzaak daarvan opgelost worden.

Tevens zie ik naast het out of stock treshold issue, nu ook een issue met simples op website level uitschakelen, zoals beschreven bij Ego Aqua. Hier maak ik zo nog een nieuw issue voor aan.

Met vriendelijke groet,
Lars Rezelman

**Comment by Fgruntjes** [comment]
Hallo,

Bedankt voor de heldere uitleg, functioneel is het duidelijk wat er fout gaat bij jullie.

Zou toch graag nog even de informatie uit de genoemde tabellen willen ontvangen. Uit jou verhaal kan ik namelijk nog niet bepalen hoe ze exact in de database staan en dat is nu juist waar het probleem bij ontstaat.

Zou je ook even de SKU's van de producten willen vermelden zodat ik met de  catalog_product_entity tabel hier een product ID van kan vinden voor de data in de andere tabellen.

Alvast bedankt!

Groeten,
Freek

**Comment by Fgruntjes** [comment]
Als ik het goed begrijp is dit issue dus niet meer relevant indien #31 hersteld is? 

Is overigens ook logische, de prijzen in de prijs index tabel zijn afwezig indien deze niet verkoopbaar zijn en in dat geval krijg je dus de 999 prijzen.

Voor nu sluit ik dan dit issue en focussen we ons op #31, indien na het het oplossen van #31 het issue nog op treed dan zullen we hem heropenen.

**Comment by LarsRezelman** [comment]
Er gaat in dit ticket inderdaad niets fout als alleen producten die verkocht mogen worden in Tweakwise komen te staan. Ofwel, als de issues uit:
https://github.com/EmicoEcommerce/Magento2TweakwiseExport/issues/31 en https://github.com/EmicoEcommerce/Magento2TweakwiseExport/issues/33 opgelost is.
