### ISSUE TITLE
Feed rekening laten houden met op website level disablen van simples

### ISSUE THREAD

**Issue by LarsRezelman** [EmicoEcommerce/Magento2TweakwiseExport-archived#33]
Bij onze implementatie bij meerdere websites en per website verschillende voorraad, prijs, status en stock status zien we het volgende probleem.

Goed om te weten is dat Score heeft 2 websites Score en Chasin'. Score verkoopt meerdere merken kleding, waaronder het merk Chasin. Chasin verkoopt het merk Chasin. Er is dus overlap in de producten. Per website kunnen de producten een andere voorraad of prijs hebben, of zelf in- of uitgeschakeld of dus in- of out of stock zijn.

- Ego Aqua:
Bij Score zijn de simples niet te koop, Bij Chasin nog wel 1 verkoopbare simple. Hierdoor zou het product niet in Tweakwise moeten staan voor Score, enkel voor Chasin.
Configurable enabled, status = in stock, qnty = 0
Er is 1 simple met stock 20, status = disabled voor Score. Op default en Chasin is de status enabled.

In dit geval zal het product enkel voor Chasin te koop moeten zijn, en zou deze niet meer voor Score ingelezen mogen worden in Tweakwise.

Environment
--
- [ ] PHP Version: (|7.0|)
- [ ] Magento Version: 2.1.10
- [ ] Magento Enterprise: (yes|)
- [ ] Tweakwise Export Version: latest 1.0.10
- [ ] Magento Deploy Mode: (production|)

**Comment by LarsRezelman** [comment]
@Fgruntjes , Om alle verwarring met de andere tickets te voorkomen. Heb jij van ons nu iets nodig om dit te kunnen reproduceren? Zo ja, dan kan je altijd morgen direct contact met ons op nemen zodat wij jou daarbij kunnen helpen, zonder vertraging.

**Comment by Fgruntjes** [comment]
Deze is naar verwachting met de wijzigingen in #31 hersteld. Zouden jullie dit kunnen testen?

**Comment by Fgruntjes** [comment]
Nog even voor de volledigheid hier. We hebben het issue kunnen reproduceren en het is met de huidige wijzigingen nog niet hersteld.

**Comment by Fgruntjes** [comment]
Issue have been fixed with the latest version V1.0.12

**Comment by LarsRezelman** [comment]
In my test today, this issue still does occur by Customer Score: (SKU: 9U00279001-090, product: shorty base)

 PHP Version: (|7.0|)
 Magento Version: 2.1.10
 Magento Enterprise: (yes|)
 Tweakwise Export Version: latest 1.1.1
 Magento Deploy Mode: (production|)

How to reproduce:
* Configurable has on default and storeview level enough stock and is enabled
* Alle te simples of the configurable are out of stock or enabled on default.*
* All the simples of the configurable are out of stock or disabled on storeview level. (It is out of stock or disabled on all the storeviews)
Result: The product cannot be sold on storeview level.
Expected result: The product isn't exported to TweakWise for the storeviews it couldn't be sold (all storeviews in this example)
Actual result: The product is exported to all the storeviews in Tweakwise. Tweakwise displays the product on the product listpage.

* It doesn't matter if there are products out of stock, because also with all the simples disabled, the product is still in the export towards Tweakwise.

**Comment by Fgruntjes** [comment]
So if I understand correctly this is the situation:

Defaullt:
- Configurable 1
  - Simple 1 (in stock, qty 3)
  - Simple 2 (in stock, qty 3)

Store 1:
- Configurable 1
  - Simple 1 (default)
  - Simple 2 (default)

Store 2
- Configurable 1
  - Simple 1 (out stock, qty 0)
  - Simple 2 (out stock, qty 0)

The expected result would be that for store 2 the configurable 1 is not exported but it is?

Other then that you also tested this:
Defaullt:
- Configurable 1
  - Simple 1 (in stock, qty 3)
  - Simple 2 (in stock, qty 3)

Store 1:
- Configurable 1
  - Simple 1 (default)
  - Simple 2 (default)

Store 2
- Configurable 1
  - Simple 1 (disabled)
  - Simple 2 (disabled)

And again configurable 1 is exported for store 2 but it should not be?

Other then that could you check your "Export out of stock combined product children" setting?

**Comment by LarsRezelman** [comment]
@Fgruntjes ,

Scenario 1, seems like it is fixed in one of your latest releases of the magento export module.
Scenario 2, still occurs at this moment.

The setting Export out of stock combined product childeren is set NO.

**Comment by Fgruntjes** [comment]
Thank you for the extra info. We just released a new version with a fix for this issue.
