### ISSUE TITLE
Add setting for adding visibility as filter parameter

### ISSUE THREAD

**Issue by Fgruntjes** [EmicoEcommerce/Magento2TweakwiseExport-archived#39]
From: EmicoEcommerce/Magento2Tweakwise#36

In Magento you can set a product visibility to 'Not individually', 'Catalog', 'Search', 'Catalog, Search'.
It would be nice if this attribute can be selected in the setting as a filter option.

In the export module you can choose already which visibility you want to export, but I would like to be able to export all products and just use a visibility filter as search parameter.

**Comment by igorwulff** [comment]
@Fgruntjes can you give us an estimate when this feature/bug is getting picked up?

**Comment by Fgruntjes** [comment]
Hello,

For prioritizing and estimates etc please ask tweakwise support, they decide when we handle what issue(s) we handle when from the github list.

Kind regards,
Freek

**Comment by Fgruntjes** [comment]
This issue has been resolved by the pull request https://github.com/EmicoEcommerce/Magento2TweakwiseExport/pull/40
