### ISSUE TITLE
Products do not have categories

### ISSUE THREAD

**Issue by mdubbelman** [EmicoEcommerce/Magento2TweakwiseExport-archived#4]
Issue Brief
--
Every product in the export have an emtpy categories tag.

Environment
--
* PHP Version: 7.0
* Magento Version: 2.1.6 CE
* Tweakwise Export Version: latest
* Magento Deploy Mode: production
* Third party modules: TIG_Buckaroo, Amasty Promo, Amasty Cart, Amasty Special Promo

Steps to reproduce
--
1. Install Magento
2. Add products and categories
4. Export the feed

Actual result
--
1. Feed gets generated
2. Products (items) and categories are added to the feed. Only the products have an empty `categories` tag

Expected result
--
We expect the products to have the right categories in path `tweakwise/items/item/categories/categoryid` but they are all emtpy

**Comment by Fgruntjes** [comment]
Hello,

Unfortunately we could not reproduce the issue with the Magento test data. Could you send me the database (fgruntjes@emico.nl) or give access to the test environment so we can debug the issue there. 

If thats an option please send the information to fgruntjes@emico.nl or give access using my public key.
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3lL78eUCbw9cxooQICUtzIGBtJrh13rHaUuepQAHUZtFRFfWc1wxouqzTuixIBgdAxJk1tmexUUPzp4lZkCuRVqlK3pabKwBTSazGSB20+AdEfPmDt+E/yDWfRTfBdxEnRcpaTqiAs2ygYfjX+RvIFinOoovuI0HATVUnv3CbaQTR1QFAhG73GNxLaeI/R8rUMtStpiL0YiQgZzVUCFY6FnLvoMLcn+p9AN+lD1KH6caJ4PoCMyE83Rc/20fM3S/Q41mMgl8n/SkyleWN409e1EpmuMYx15rIliKXQoPYmpBsnzRW3IPgYXuW0oJsHg8fzYZosaP1HYaeqcl6X+3D fgruntjes@emico.nl
```

**Comment by Fgruntjes** [comment]
Categories are taken from the catalog_category_product_index table. With the provided database the reindexing this table does not fill this table as expected. For example product with id 13298 has a few categories but even after reindex no records in the index table.

Also as seen in the full export there are more products with categories.
```
[13:00:32]-[Freeks-MacBook-Pro]-[master ✗]-[/Volumes/WWW/tweakwise2-ce.dev/var/feeds] $
▶ cat tweakwise.xml.tmp | grep -B 5 -A 2 "<categories>" | more
<?xml version="1.0" encoding="UTF-8"?>
<tweakwise>
    <shop><![CDATA[B2C]]></shop>
    <timestamp><![CDATA[2017-05-19T10:53:28.000000+00:00]]></timestamp>
    <categories>
        <category>
            <categoryid>1</categoryid>
--
--
        <item>
            <id>1000114</id>
            <price>17.5000</price>
            <name><![CDATA[TIGI Bed Head Dumb Blonde Smoothing Stuff]]></name>
            <stock>0</stock>
            <categories>
                <categoryid>100011488</categoryid>
            </categories>
--
--
        <item>
            <id>1000121</id>
            <price>10.9500</price>
            <name><![CDATA[TIGI Bed Head Superstar Queen for a Day Hairspray]]></name>
            <stock>0</stock>
            <categories>
                <categoryid>10001262</categoryid>
            </categories>
```

Conclusion is that this is a data issue and not an issue with the extension.
