### ISSUE TITLE
Disabled for store product is exported to XML

### ISSUE THREAD

**Issue by SerhiyShkolyarenko** [EmicoEcommerce/Magento2TweakwiseExport-archived#41]
Issue Brief
--
What is the purpose of this issue? Explain the background context.

Environment
--
- [x] PHP Version: 7.0
- [x] Magento Version: 2.1.6
- [x] Magento Enterprise: no
- [x] Tweakwise Export Version: 1.1.2
- [x] Magento Deploy Mode: production
- [x] Third party modules: none

Steps to reproduce
--
1. Install Magento from `develop` branch.
2. Create 4 stores.
3. Create simple product.
4. Disable the product for one store, for examle Store2.
5. Set special price for this product on a global scope.
6. run "./bin/magento tweakwise:export"

Actual result
--
1. File var/feeds/tweakwise.xml contains this product declared for all stores.
2. For the Store2 tweakwise imports it with regular price because special price field is empty.

Expected result
--
- [ ] File var/feeds/tweakwise.xml contains this product declared for all stores except Store2.

**Comment by Fgruntjes** [comment]
Hello,

Enabled / disabled is a global attribute see:
![screenshot-tweakwise2-ce-issue-41 test-2018 03 27-17-33-42](https://user-images.githubusercontent.com/984466/37978964-9fe97b34-31e7-11e8-9e11-6dc122573501.png)

So to test this we created 4 websites with one product disabled
![nimbus-record-video-2018-03-27-17-54-44](https://user-images.githubusercontent.com/984466/37979370-be572dd6-31e8-11e8-8f2b-5fe0a57db6ea.gif)

This works as expected.

Please provide more information on how to reproduce the issue.

**Comment by SerhiyShkolyarenko** [comment]
Hello @Fgruntjes!
I mean step 4 as "Unassign the product for one store, for examle Store2."

**Comment by SerhiyShkolyarenko** [comment]
@Fgruntjes, thank you!
