### ISSUE TITLE
`catalog_product_entity_int.value` is exported when `eav_attribute_option.option_id` is removed

### ISSUE THREAD

**Issue by jasperzeinstra** [EmicoEcommerce/Magento2TweakwiseExport-archived#42]
Issue Brief
--
For example create a product with the attribute `color` and select the option `Light blue`. When Tweakwise export is handeling this product it will transform `option_id` to the name of the option in method `\Emico\TweakwiseExport\Model\Write\Products::normalizeAttributeValue`.

But when you delete the option from the attribute options list, the initial option id value is not removed from `catalog_product_entity_int`. This is default Magento behaviour in M1 and in M2. Now when the method `\Emico\TweakwiseExport\Model\Write\Products::normalizeAttributeValue` is being fired the mapping doesn't provide a name for the `option_id` and instead of setting the value to nothing the `option_id` is still being used resulting in a filter with names and id's.

![screen shot 2018-03-12 at 13 11 20](https://user-images.githubusercontent.com/9214557/37283054-e6dfdbc0-25f6-11e8-9e7f-2f93b6882ac8.png)

Environment
--
- [x] PHP Version: (7.0)
- [x] Magento Version: 2.2.3
- [x] Magento Enterprise: yes
- [x] Tweakwise Export Version: V1.1.2
- [x] Magento Deploy Mode: production
- [x] Third party modules: -

Steps to reproduce
--
1. Create product with color attribute and select a value
2. Initiate an export to Tweakwise
3. Remove chosen color value form attribute options list
4. Initiate an export to Tweakwise

Actual result
--
1. `option_id` is exported to Tweakwise

Expected result
--
- [ ] Empty value for `color` should be set in Tweakwise

**Comment by martijnrmediact** [comment]
@Fgruntjes  this is still an issue in the latest version of Tweakwise with Magento 2.2.5

**Comment by jasperzeinstra** [comment]
@martijnrmediact @Fgruntjes this issue has been resolved, but we still have an issue with attributes that don't use a source model. There's a pull request open for this issue: https://github.com/EmicoEcommerce/Magento2TweakwiseExport/pull/55
