### ISSUE TITLE
Area Code is not set 

### ISSUE THREAD

**Issue by govereem** [EmicoEcommerce/Magento2TweakwiseExport-archived#44]
## Issue Brief
When running command: `bin/magento tweakwise:export` we get an error.
`
[Magento\Framework\Exception\LocalizedException]  
  Area code is not set  
`
Environment
 PHP Version: (7.0)
 Magento Version: 2.2.3
 Magento Enterprise: yes
 Tweakwise Export Version: V1.1.2
 Magento Deploy Mode: developer & production
 Third party modules: -

### Steps to reproduce
Simple run the export command

### Actual result
Area code is not set , error

### Expected result
No errors

### Extra information
The error is comming from https://github.com/magento/magento2/blame/2.2-develop/lib/internal/Magento/Framework/Session/SidResolver.php#L94 changed in Magento 2.2.3
The area code is not set, because appState is empty from the constructor and the \Magento\Framework\App\ObjectManager::getInstance()->get(State::class), will not have the area code set.
https://github.com/magento/magento2/blame/2.2-develop/lib/internal/Magento/Framework/Session/SidResolver.php#L85

For the moment we solved the problem by added some lines of code, but not a preferred solution.
https://github.com/EmicoEcommerce/Magento2TweakwiseExport/blob/master/src/Console/Command/ExportCommand.php#L93

            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $state = $objectManager->get('Magento\Framework\App\State');
            $state->setAreaCode(Area::AREA_CRONTAB);

This is the same object instance used by SidResolver in the constructor and is our work around for now.

**Comment by martijnrmediact** [comment]
@Fgruntjes this is also a problem for us for some clients that moved to magento 2.2.3. Can this be resolved?

**Comment by Fgruntjes** [comment]
Hello,

This seems to be another issue, we tested with a new installation from 2.2.3 + sample data and the export runs without a problem.

See:
```
▶ ./bin/magento -V
Magento CLI version 2.2.3

▶ ./bin/magento tweakwise:export
Feed written to /Volumes/WWW/tweakwise2-ce/var/feeds/tweakwise.xml in 13.76s using 58Mb memory
```
