### ISSUE TITLE
Skip products in export that have blank product name

### ISSUE THREAD

**Issue by duckchip** [EmicoEcommerce/Magento2TweakwiseExport-archived#47]
Issue Brief
--
When the attribute "name" in magento is left blank on some products and afterwards an import in tweakwise is done of the exported magento data, the import fails. 

Could it be possible to skip those products that don't have a product name?

Steps to reproduce
--
1. Create product without product name
2. Run Tweakwise export in Magento
4. Import the data from step 2 in Tweakwise

Actual result
--
1. failed Tweakwise import

Expected result
--
1. Successful Tweakwise import

**Comment by Fgruntjes** [comment]
Since Magento does not allow saving products without a name this should definitely be considered an issue with the data.

However we are aware that some data import methods allow this to happen and therefore will add an extra safeguard for this situation.
