### ISSUE TITLE
Disabled products are not skipped

### ISSUE THREAD

**Issue by vichi-techtwo** [EmicoEcommerce/Magento2TweakwiseExport-archived#5]
Issue Brief
--
What is the purpose of this issue? Explain the background context.

Environment
--
* PHP Version: 7.0
* Magento Version: 2.1.6 CE
* Tweakwise Export Version: 1.0.0
* Magento Deploy Mode: production + development

Steps to reproduce
--
1. Install Magento from `develop` branch.
2. Export product with the status disabled to Tweakwise.
3. Run the command "magento tweakwise:export"

Actual result
--
1. The XML feed returns an empty price due to the product is not available in the index table "catalog_product_index_price".

Expected result
--
1. The XML feed should skip the disabled products.

Solution
--
1. In \Emico\TweakwiseExport\Model\Write\Products\Iterator::skipEntity the wrong condition is checked `(!$entity['status'])` should be `($entity['status'] == 2)`
vendor/emico/tweakwise-export/src/Model/Write/Products/Iterator.php:194

**Comment by Fgruntjes** [comment]
Thnx for the issue. To increase the speed for when an issue is resolved a pull request would be greatly appreciated.
