### ISSUE TITLE
Prices generated by Price rules are not available to productorder on pricing

### ISSUE THREAD

**Issue by MaartenHendriksJB** [EmicoEcommerce/Magento2TweakwiseExport-archived#50]
JohnBeerens.com is a webshop with 200+ brands. Several brands have a discount. We use pricing rules to set for example 10% discount to brand-X. This works fine in Magento. However no "special price is filled. So the feed that goes to tweakwise does not have an special price to use for ordering products form lowest price tot highest price.

Environment
--
- [ ] Magento Version: 2
- [ ] Magento Enterprise: no
- [ ] Tweakwise Export Version:
- [ ] Magento Deploy Mode: production
- [ ] Third party modules:

Actual result
--
In the feed there is not field with the price after the price ruls

Expected result
--
List the expected results as a bullet list of expectations
price in the deed so it is possible to order on pricing from low tot high

**Comment by edwinljacobs** [comment]
Hello, thanks for reporting this.

I assume that the mentioned discount is managed via a catalog price rule (so not a cart price rule), otherwise it is impossible to determine this discount while exporting, is this true?

Could you specify what the configuration value of the "Tweakwise > Export > Price Field" field is?
In your case this should be any setting where Final Price takes priority over price (i.e. any setting where Final Price > Price) is present. The configuration which covers most bases is: Final Price > Price > Min Price. Which configuration do you use?

With kind regards

**Comment by MaartenHendriksJB** [comment]
Hello,

Yes that’s correct. It’s a catalog price rule.

The current setting is: Final Price > Price > Min Price
Kind Regards,
Maarten Hendriks
JohnBeerens.com
Tijvoortsebaan 8
5051 HJ Goirle
tel.: 013-530 20 10
e-mail: maarten@johnbeerens.com<mailto:maarten@johnbeerens.com>
internet: www.JohnBeerens.com<http://www.johnbeerens.com/>
[1513759542254_handtekening-mail.jpg]
[facebook-icon]<https://www.facebook.com/JohnBeerensWebshop>      [instagram-icon] <http://instagram.com/johnbeerensshop>        [linkedin-icon] <https://www.linkedin.com/company/2636045>       [twitter-icon] <http://twitter.com/JohnBeerensShop>        [youtube-icon] <http://www.youtube.com/user/TheJohnbeerens>

Van: edwinljacobs [mailto:notifications@github.com]
Verzonden: donderdag 31 mei 2018 13:26
Aan: EmicoEcommerce/Magento2TweakwiseExport <Magento2TweakwiseExport@noreply.github.com>
CC: Maarten Hendriks | JohnBeerens.com <maarten@johnbeerens.com>; Author <author@noreply.github.com>
Onderwerp: Re: [EmicoEcommerce/Magento2TweakwiseExport] Prices generated by Price rules are not available to productorder on pricing (#50)


Hello, thanks for reporting this.

I assume that the mentioned discount is managed via a catalog price rule (so not a cart price rule), otherwise it is impossible to determine this discount while exporting, is this true?

Could you specify what the configuration value of the "Tweakwise > Export > Price Field" field is?
In your case this should be any setting where Final Price takes priority over price (i.e. any setting where Final Price > Price) is present. The configuration which covers most bases is: Final Price > Price > Min Price. Which configuration do you use?

With kind regards

**Comment by edwinljacobs** [comment]
Hello,

This seems to be a magento issue, see: https://github.com/magento/magento2/issues/7465
The problem being that the prices generated by the catalogrule are not accounted for in the catalog_product_index_price table. Since this the data source for the export the prices are not correct.

In the issue description we see that according to magento this is fixed in 2.3 What version are your running? 

With kind regards

**Comment by MaartenHendriksJB** [comment]
Hello,

We are running on 2.1.6. We are planning to go to 2.2.2. in the upcomming 2 weeks. Our websdesigner say’s 2.3 is only in beta now and an official release is not announced so far. Do you know of a patch wil be released to solve this in 2.2.2?
Kind Regards,
Maarten Hendriks
JohnBeerens.com
Tijvoortsebaan 8
5051 HJ Goirle
tel.: 013-530 20 10
e-mail: maarten@johnbeerens.com<mailto:maarten@johnbeerens.com>
internet: www.JohnBeerens.com<http://www.johnbeerens.com/>
[1513759542254_handtekening-mail.jpg]
[facebook-icon]<https://www.facebook.com/JohnBeerensWebshop>      [instagram-icon] <http://instagram.com/johnbeerensshop>        [linkedin-icon] <https://www.linkedin.com/company/2636045>       [twitter-icon] <http://twitter.com/JohnBeerensShop>        [youtube-icon] <http://www.youtube.com/user/TheJohnbeerens>

Van: edwinljacobs [mailto:notifications@github.com]
Verzonden: woensdag 6 juni 2018 12:59
Aan: EmicoEcommerce/Magento2TweakwiseExport <Magento2TweakwiseExport@noreply.github.com>
CC: Maarten Hendriks | JohnBeerens.com <maarten@johnbeerens.com>; Author <author@noreply.github.com>
Onderwerp: Re: [EmicoEcommerce/Magento2TweakwiseExport] Prices generated by Price rules are not available to productorder on pricing (#50)


Hello,

This seems to be a magento issue, see: magento/magento2#7465<https://github.com/magento/magento2/issues/7465>
The problem being that the prices generated by the catalogrule are not accounted for in the catalog_product_index_price table. Since this the data source for the export the prices are not correct.

In the issue description we see that according to magento this is fixed in 2.3 What version are your running?

With kind regards

**Comment by MaartenHendriksJB** [comment]
Hello,

Can you please respond to below?
Kind Regards,
Maarten Hendriks
JohnBeerens.com
Tijvoortsebaan 8
5051 HJ Goirle
tel.: 013-530 20 10
e-mail: maarten@johnbeerens.com<mailto:maarten@johnbeerens.com>
internet: www.JohnBeerens.com<http://www.johnbeerens.com/>
[1513759542254_handtekening-mail.jpg]
[facebook-icon]<https://www.facebook.com/JohnBeerensWebshop>      [instagram-icon] <http://instagram.com/johnbeerensshop>        [linkedin-icon] <https://www.linkedin.com/company/2636045>       [twitter-icon] <http://twitter.com/JohnBeerensShop>        [youtube-icon] <http://www.youtube.com/user/TheJohnbeerens>

Van: Maarten Hendriks | JohnBeerens.com
Verzonden: dinsdag 12 juni 2018 15:20
Aan: 'EmicoEcommerce/Magento2TweakwiseExport' <reply@reply.github.com>; EmicoEcommerce/Magento2TweakwiseExport <Magento2TweakwiseExport@noreply.github.com>
CC: Author <author@noreply.github.com>
Onderwerp: RE: [EmicoEcommerce/Magento2TweakwiseExport] Prices generated by Price rules are not available to productorder on pricing (#50)

Hello,

We are running on 2.1.6. We are planning to go to 2.2.2. in the upcomming 2 weeks. Our websdesigner say’s 2.3 is only in beta now and an official release is not announced so far. Do you know of a patch wil be released to solve this in 2.2.2?
Kind Regards,
Maarten Hendriks
JohnBeerens.com
Tijvoortsebaan 8
5051 HJ Goirle
tel.: 013-530 20 10
e-mail: maarten@johnbeerens.com<mailto:maarten@johnbeerens.com>
internet: www.JohnBeerens.com<http://www.johnbeerens.com/>
[1513759542254_handtekening-mail.jpg]
[facebook-icon]<https://www.facebook.com/JohnBeerensWebshop>      [instagram-icon] <http://instagram.com/johnbeerensshop>        [linkedin-icon] <https://www.linkedin.com/company/2636045>       [twitter-icon] <http://twitter.com/JohnBeerensShop>        [youtube-icon] <http://www.youtube.com/user/TheJohnbeerens>

Van: edwinljacobs [mailto:notifications@github.com]
Verzonden: woensdag 6 juni 2018 12:59
Aan: EmicoEcommerce/Magento2TweakwiseExport <Magento2TweakwiseExport@noreply.github.com<mailto:Magento2TweakwiseExport@noreply.github.com>>
CC: Maarten Hendriks | JohnBeerens.com <maarten@johnbeerens.com<mailto:maarten@johnbeerens.com>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Onderwerp: Re: [EmicoEcommerce/Magento2TweakwiseExport] Prices generated by Price rules are not available to productorder on pricing (#50)


Hello,

This seems to be a magento issue, see: magento/magento2#7465<https://github.com/magento/magento2/issues/7465>
The problem being that the prices generated by the catalogrule are not accounted for in the catalog_product_index_price table. Since this the data source for the export the prices are not correct.

In the issue description we see that according to magento this is fixed in 2.3 What version are your running?

With kind regards

**Comment by MaartenHendriksJB** [comment]
Hello,

We schedult the update to go to 2.2.2. this and next week. However we set this on hold because of the last reaction below with 2.3 was pointed as an solution.

Can you please resprond to below so we now what to do?
Kind Regards,
Maarten Hendriks
JohnBeerens.com
Tijvoortsebaan 8
5051 HJ Goirle
tel.: 013-530 20 10
e-mail: maarten@johnbeerens.com<mailto:maarten@johnbeerens.com>
internet: www.JohnBeerens.com<http://www.johnbeerens.com/>
[1513759542254_handtekening-mail.jpg]
[facebook-icon]<https://www.facebook.com/JohnBeerensWebshop>      [instagram-icon] <http://instagram.com/johnbeerensshop>        [linkedin-icon] <https://www.linkedin.com/company/2636045>       [twitter-icon] <http://twitter.com/JohnBeerensShop>        [youtube-icon] <http://www.youtube.com/user/TheJohnbeerens>

Van: Maarten Hendriks | JohnBeerens.com
Verzonden: dinsdag 19 juni 2018 17:40
Aan: 'EmicoEcommerce/Magento2TweakwiseExport' <reply@reply.github.com>; 'EmicoEcommerce/Magento2TweakwiseExport' <Magento2TweakwiseExport@noreply.github.com>
CC: 'Author' <author@noreply.github.com>
Onderwerp: RE: [EmicoEcommerce/Magento2TweakwiseExport] Prices generated by Price rules are not available to productorder on pricing (#50)

Hello,

Can you please respond to below?
Kind Regards,
Maarten Hendriks
JohnBeerens.com
Tijvoortsebaan 8
5051 HJ Goirle
tel.: 013-530 20 10
e-mail: maarten@johnbeerens.com<mailto:maarten@johnbeerens.com>
internet: www.JohnBeerens.com<http://www.johnbeerens.com/>
[1513759542254_handtekening-mail.jpg]
[facebook-icon]<https://www.facebook.com/JohnBeerensWebshop>      [instagram-icon] <http://instagram.com/johnbeerensshop>        [linkedin-icon] <https://www.linkedin.com/company/2636045>       [twitter-icon] <http://twitter.com/JohnBeerensShop>        [youtube-icon] <http://www.youtube.com/user/TheJohnbeerens>

Van: Maarten Hendriks | JohnBeerens.com
Verzonden: dinsdag 12 juni 2018 15:20
Aan: 'EmicoEcommerce/Magento2TweakwiseExport' <reply@reply.github.com>; EmicoEcommerce/Magento2TweakwiseExport <Magento2TweakwiseExport@noreply.github.com<mailto:Magento2TweakwiseExport@noreply.github.com>>
CC: Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Onderwerp: RE: [EmicoEcommerce/Magento2TweakwiseExport] Prices generated by Price rules are not available to productorder on pricing (#50)

Hello,

We are running on 2.1.6. We are planning to go to 2.2.2. in the upcomming 2 weeks. Our websdesigner say’s 2.3 is only in beta now and an official release is not announced so far. Do you know of a patch wil be released to solve this in 2.2.2?
Kind Regards,
Maarten Hendriks
JohnBeerens.com
Tijvoortsebaan 8
5051 HJ Goirle
tel.: 013-530 20 10
e-mail: maarten@johnbeerens.com<mailto:maarten@johnbeerens.com>
internet: www.JohnBeerens.com<http://www.johnbeerens.com/>
[1513759542254_handtekening-mail.jpg]
[facebook-icon]<https://www.facebook.com/JohnBeerensWebshop>      [instagram-icon] <http://instagram.com/johnbeerensshop>        [linkedin-icon] <https://www.linkedin.com/company/2636045>       [twitter-icon] <http://twitter.com/JohnBeerensShop>        [youtube-icon] <http://www.youtube.com/user/TheJohnbeerens>

Van: edwinljacobs [mailto:notifications@github.com]
Verzonden: woensdag 6 juni 2018 12:59
Aan: EmicoEcommerce/Magento2TweakwiseExport <Magento2TweakwiseExport@noreply.github.com<mailto:Magento2TweakwiseExport@noreply.github.com>>
CC: Maarten Hendriks | JohnBeerens.com <maarten@johnbeerens.com<mailto:maarten@johnbeerens.com>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Onderwerp: Re: [EmicoEcommerce/Magento2TweakwiseExport] Prices generated by Price rules are not available to productorder on pricing (#50)


Hello,

This seems to be a magento issue, see: magento/magento2#7465<https://github.com/magento/magento2/issues/7465>
The problem being that the prices generated by the catalogrule are not accounted for in the catalog_product_index_price table. Since this the data source for the export the prices are not correct.

In the issue description we see that according to magento this is fixed in 2.3 What version are your running?

With kind regards

**Comment by edwinljacobs** [comment]
Hello,

The scheduled release date for 2.3 is "somewhere end of this year" which is still a long way from now. We are currently discussing with Tweakwise if we should make a compatibility module for this issue.

**Comment by maksymhryb** [comment]
Hi all, I've tried to fix this issue in the following pull request https://github.com/EmicoEcommerce/Magento2TweakwiseExport/pull/58

It allows you to include catalog product price for NOT_LOGGED_IN in customer group to the feed.
Would be nice if someone can review and test this.


Kind regards.

**Comment by edwinljacobs** [comment]
Hello this has been implemented in the latest release: v1.2.2. Backend configuration should be adjusted to Rule price > Final price > Price > Min Price, rerun the export and the rule prices should be included. Note that when magento releases 2.3 this fix is redundant so it could be that we drop this code if and when we drop support for magento < 2.3. Credits to @maksim-grib for the PR. If all is well you can close this issue

With kind regards

**Comment by edwinljacobs** [comment]
I will close this issue. If you feel that this is incorrect feel free to open a new issue.
