### ISSUE TITLE
Sku will not be in the tweakwise.xml due to last changes

### ISSUE THREAD

**Issue by govereem** [EmicoEcommerce/Magento2TweakwiseExport-archived#51]
Issue Brief
--
What is the purpose of this issue? Explain the background context.
Because sku is needed for some of tweakwise features like google analytics and bestsellers results.
I did some investigation, it worked before de last changes of a month ago. 

It seems this change, removed some needed attributes, function normalizeAttributeValue
https://github.com/EmicoEcommerce/Magento2TweakwiseExport/commit/a0762ea8480028876e0315a7120f43bb098ece06#diff-98035dc608c5cfe3429d8cd1cb57758cR306

The solution for now, is using a older tweakwise version or replace 
```
$result[] = $map[$value] ?? null; 
Change back to 
$result[] = isset($map[$value]) ? $map[$value] : $value;
```

Environment
--
- [ ] PHP Version: (5.6|7.0|7.1)
- [ ] Magento Version:
- [ ] Magento Enterprise: (yes|no)
- [ ] Tweakwise Export Version:
- [ ] Magento Deploy Mode: (production|development)
- [ ] Third party modules:

Steps to reproduce
--
1. Install Magento from `develop` branch.
2. [Example] Export configurable product with multiple children and 2 configurable attributes to Tweakwise.
4. ...

Actual result
--
1. [Example] Error message appears: "Cannot save quote".
2. [Screenshot, logs]
3. ...

Expected result
--
List the expected results as a bullet list of expectations
- [ ] [Example] Configurable product added to the shopping cart.
- [ ] ...

**Comment by edwinljacobs** [comment]
There is a fix for this issue and this will be available with the next release

**Comment by edwinljacobs** [comment]
Sku should be exported correctly in release 1.2.0

**Comment by EduardSelles** [comment]
Hi Gideon,
please close this issue if the solution is okay.
thank you!
