### ISSUE TITLE
Feature request: stock percentage attribute

### ISSUE THREAD

**Issue by EduardSelles** [EmicoEcommerce/Magento2TweakwiseExport-archived#52]
Add extra attribute in the feed which indicates how many percent of the product variants are available. Similar function as already available in M1 export extension.

**Comment by edwinljacobs** [comment]
This has been added released with version 1.2.1, here are the release notes of that version:

Added stock_percentage attribute to export. This is configurable (use it yes or no) and it will export the percentage of child products that are in stock. Example: if a composite (type_id is not simple) product has 8 children for which there are 4 in stock then stock_percentage will have value 50 (as in 50%)

**Comment by EduardSelles** [comment]
Well done Edwin. Thanks!
