### ISSUE TITLE
XML feed return space value for empty attributes

### ISSUE THREAD

**Issue by vichi-techtwo** [EmicoEcommerce/Magento2TweakwiseExport-archived#6]
Issue Brief
--
What is the purpose of this issue? Explain the background context.

Environment
--
* PHP Version: 7.0
* Magento Version: 2.1.6 CE
* Tweakwise Export Version: 1.0.0
* Magento Deploy Mode: production + development

Steps to reproduce
--
1. Install Magento from `develop` branch.
2. Export product with empty attribute values to Tweakwise..
3. Run the command "magento tweakwise:export"

Actual result
--
1. The XML feed returns the value " " (empty space) for empty attributes. Example:
`<attribute datatype="text">
                    <name><![CDATA[special_price]]></name>
                    <value><![CDATA[ ]]></value>
                </attribute>`

Expected result
--
1. Node should skipped or empty.

**Comment by Fgruntjes** [comment]
Added fix, please check out your data import, only using the database connection directly was I able to insert a null value in catalog_product_entity_decimal table.
