### ISSUE TITLE
Product categories always limited to 1

### ISSUE THREAD

**Issue by vichi-techtwo** [EmicoEcommerce/Magento2TweakwiseExport-archived#7]
Issue Brief
--
What is the purpose of this issue? Explain the background context.

Environment
--
* PHP Version: 7.0
* Magento Version: 2.1.6 CE
* Tweakwise Export Version: 1.0.0
* Magento Deploy Mode: production + development
* Third party modules:

Steps to reproduce
--
1. Install Magento from `develop` branch.
2. Export product assigned to multiple categories to Tweakwise.
3. Run the command "magento tweakwise:export"

Solution
--
In \Emico\TweakwiseExport\Model\Write\Products\Iterator::getEntityCategoriesBatch the line number vendor/emico/tweakwise-export/src/Model/Write/Products/Iterator.php:286 should be `if (!isset($result[$entityId])) {
                $result[$entityId] = [];
            }`

Actual result
--
1. The XML feed returns only 1 category instead of multiple.

Expected result
--
1. The XML feed should return all categories the product is assigned to.

**Comment by Fgruntjes** [comment]
Thanx for the suggestion!
