### ISSUE TITLE
Double colon in tweakwise export command in README

### ISSUE THREAD

**Issue by robhuijben** [EmicoEcommerce/Magento2TweakwiseExport-archived#83]
Small issue in the README.md file. There's a double colon in the tweakwise:export command in the Usage section, which should be a single colon.

```php bin/magento tweakwise::export```

should be

```php bin/magento tweakwise:export```

**Comment by edwinljacobs** [comment]
Thanks ill update that

**Comment by edwinljacobs** [comment]
Updated in the master branch, this will included in the next release. 
Thanks for pointing that out :)

With kind regards
