### ISSUE TITLE
Setup:di:compile fails on version 1.0.1

### ISSUE THREAD

**Issue by ghost** [EmicoEcommerce/Magento2TweakwiseExport-archived#9]
When running setup:di:compile the command crashes because a ReflectionException occurs.
The Exception says "Class   does not exist"

Environment
--
* PHP Version: (7.0.6)
* Magento Version: 2.1.6
* Tweakwise Export Version: 1.0.1
* Magento Deploy Mode: production

Steps to reproduce
--
1. Run php bin/magento setup:di:compile

Actual result
--
1. Compilation was started.
Area configuration aggregation... 5/7 [====================>-------]  71% 36 secs 210.0 MiBMiB

  [ReflectionException]
  Class   does not exist

Expected result
--
1. Compilation was started.
Interception cache generation... 7/7 [============================] 100% 56 secs 300.0 MiBBMiB
Generated code and dependency injection configuration successfully.

**Comment by vichi-techtwo** [comment]
I've created a patch for this issue.

[TWEAKWISE-1.0.1-2017-06-19.patch.zip](https://github.com/EmicoEcommerce/Magento2TweakwiseExport/files/1085399/TWEAKWISE-1.0.1-2017-06-19.patch.zip)

**Comment by Fgruntjes** [comment]
Could you make the patch into a pull request?

**Comment by ghost** [comment]
Could you make a new release with this fix since version 1.0.1 is not working.

**Comment by Fgruntjes** [comment]
@miketechtwo We have created a new version, thanks for reminding.
