### ISSUE TITLE
Enabled setting not working as expected

### ISSUE THREAD

**Issue by arnoudhgz** [EmicoEcommerce/Magento2TweakwiseExport-archived#93]
When you disable the export (set it to 'No') it still generates an export according to the configured schedule.
You need to make the schedule field empty to actually disable it.

I would expect it to not run at all when export is set to no, so in https://github.com/EmicoEcommerce/Magento2TweakwiseExport/blob/master/src/Cron/Export.php a check if it's enabled.

**Comment by edwinljacobs** [comment]
The reason this is the case is that you could disable the export globally but enable it for just one store. The cron task should then export that store.

We could verify if it is disabled for all stores but I don't think that it adds anything particularly useful.
Perhaps check for single store mode and export disabled?

**Comment by Hnto** [comment]
@arnoudhgz I'm closing the issue. The fix will be available in the latest version.
