### ISSUE TITLE
Feed doesn't export out of stock products

### ISSUE THREAD

**Issue by gunnie-agency** [EmicoEcommerce/Magento2TweakwiseExport-archived#97]
After the last update, we removed the following check from ExportEntity.php, because all children were being exported.
```
if ($this->stockConfiguration->isShowOutOfStock($this->store->getId())) {
      return true;
}
```
This fix was actually wrong, because now the configurable products will only being exported if they have stock and that was where the check for was. After fixing this, we have to make sure that all configurables get exported (even the out of stock) and that the out of stock children won't be exported, so the size filter will work.
--
What is the purpose of this issue? Explain the background context.

Environment
--
- [ ] PHP Version: (5.6|7.0|7.1)
- [ ] Magento Version:
- [ ] Magento Enterprise: (yes|no)
- [ ] Tweakwise Export Version:
- [ ] Magento Deploy Mode: (production|development)
- [ ] Third party modules:

Steps to reproduce
--
1. Install Magento from `develop` branch.
2. [Example] Export configurable product with multiple children and 2 configurable attributes to Tweakwise.
4. ...

Actual result
--
1. [Example] Error message appears: "Cannot save quote".
2. [Screenshot, logs]
3. ...

Expected result
--
List the expected results as a bullet list of expectations
- [ ] [Example] Configurable product added to the shopping cart.
- [ ] ...

**Comment by Hnto** [comment]
@gunneman I'm closing this issue since it has been fixed in the latest version
